name: reusable
on: 
  workflow_call: 
    inputs:
      artifact-name:
        description: the name of the deployable artifact files
        required: false
        default: dist
        type: string


jobs:
  usable:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: display files
        run: ls
      - name: deploy files 
        run: echo " deploying and upgarding files"